### ISSUE TITLE
Error: Module cannot be found - '@/key/mnemonic'

### ISSUE THREAD

**Issue by atulgokul** [CasperDash/casper-storage#17]
Tried to run the CasperHD Wallet  (with the keyphrase) Node JS code. Found the above error. 

Have a look into this.

![capture](https://user-images.githubusercontent.com/98705414/161131383-7f7bc9eb-f161-4fa1-ba03-d0aec30d72c9.jpg)

**Comment by codsay** [comment]
@atulgokul thanks for reaching out, I was falling in trap for a sugar typescript configuration ;) -  (paths)
I just released a new minor version with some improvements and also a fix for that (0.1.17)
