### ISSUE TITLE
Custodial verification 

### ISSUE THREAD

**Issue by Atul-666** [CasperDash/casper-storage#19]
Hi, just wanted to know if there is any method out there by which u can sign/verify the messages in Casper blockchain system ?

(P.S. I 'm new to this)

![1](https://user-images.githubusercontent.com/65850590/165086600-f375ec46-7b93-4855-af71-501fd1914059.PNG)

**Comment by djhahe** [comment]
Hi @Atul-666 ,
To sign/verify message/deploy pls use casper-js-sdk
